linters:
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - gosec
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unparam
    - unused
    - depguard
    - dogsled
    - dupl
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - revive
    - stylecheck
    - tparallel
    - unconvert
    - unused
    - whitespace
    - wrapcheck
    - govet
