builds:
  - id: tfvc
    binary: tfvc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

brews:
  - tap:
      owner: tfverch
      name: homebrew-tfvc
    homepage: https://github.com/tfverch/tfvc
    description: tfvc is a tool for checking terraform provider and module versions are up to date

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates: ["tfverch/{{ .ProjectName }}:{{ .Tag }}-amd64"]
    ids:
      - tfvc
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --build-arg
      - --no-cache
      - --platform=linux/amd64
  - image_templates: ["tfverch/{{ .ProjectName }}:{{ .Tag }}-arm64v8"]
    ids:
      - tfvc
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
  - image_templates: ["tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-amd64"]
    ids:
      - tfvc
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates: ["tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-arm64v8"]
    ids:
      - tfvc
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8

docker_manifests:
  - name_template: "tfverch/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - tfverch/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}:latest"
    image_templates:
      - tfverch/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}"
    skip_push: auto
    image_templates:
      - tfverch/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}"
    image_templates:
      - tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}-alpine:latest"
    image_templates:
      - tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}-alpine:v{{ .Major }}.{{ .Minor }}"
    skip_push: auto
    image_templates:
      - tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}-alpine:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}-ci:{{ .Tag }}"
    image_templates:
      - tfverch/{{ .ProjectName }}-ci:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}-ci:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}-ci:latest"
    image_templates:
      - tfverch/{{ .ProjectName }}-ci:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}-ci:{{ .Tag }}-amd64
  - name_template: "tfverch/{{ .ProjectName }}-ci:v{{ .Major }}.{{ .Minor }}"
    skip_push: auto
    image_templates:
      - tfverch/{{ .ProjectName }}-ci:{{ .Tag }}-arm64v8
      - tfverch/{{ .ProjectName }}-ci:{{ .Tag }}-amd64
